### PR TITLE
RAM defaults and Status Image

### PR DESCRIPTION
**Pull request by Penagwin**
This commit will change the defaults memory to 2048 MB instead of 1024 MB, as to help with newer modpacks.

Also added a status image into the main part of the launcher, that has a config to change the URL of the desired image. Defaults to Alice as of now.

### CODE REVIEW

**Comment by Slind14** [comment]
the default shouldn't be higher than 1024 MB unless you build a 32 bit detection into it

**Comment by Penagwin** [comment]
Great point. I will add this shortly.

**Comment by Penagwin** [comment]
It should now detect 32 system and set the max ram to 1024 MB and the permgen to 128MB, if those values were any higher.


*Should* be all set now. If somebody could test this on a 32 bit setup that would be great.

**Comment by Slind14** [comment]
Not sure if it would be interesting for you:
https://github.com/MineYourMind/launcher/commit/cfe8c27dfc1cfc292a51374b54cb23b6ffd074dc#diff-ac7283459fbbffa7db9c7e265f035fbbR123
We do notify the user if he has 32bit java but a 64bit OS.

**Comment by Penagwin** [comment]
I will change my code so I have a dialog similar to yours.

Although, you depend on the Environment Variable PROCESSOR_ARCHITEW6432
Out of curiosity, how do you know that will exist across Linux/Mac/Windows?

**Comment by Slind14** [comment]
took us quite some time to find one that covers all OS. The current one is tested on Linux, Solaris, Mac and Windows:
https://github.com/MineYourMind/launcher/blob/me/src/main/java/com/skcraft/launcher/dialog/LauncherFrame.java#L127

**Comment by sk89q** [comment]
IMO:

1. Status image goes best in the welcome page
2. Calling `e.printStackTrace();` is bad, especially when getting a logger is so easy

**Comment by Penagwin** [comment]
Slind14, I merged in your commit the warning dialog. However I had to change the detection method because I got a null pointer on my system. Not sure how we can detect the system architecture from java.

(Tested with bin32-jre from the aur as well)

**Comment by Slind14** [comment]
mhh interesting, it works fine for us on at least windows, mac and linux. We have around 1000 active users.

**Comment by Penagwin** [comment]
System.getenv("PROCESSOR_ARCHITEW6432");

I get null  with this. I'm using arch linux, and judging by the W in the variable name it is windows only.

**Comment by Slind14** [comment]
This is exactly why the if is there:
https://github.com/MineYourMind/launcher/blob/me/src/main/java/com/skcraft/launcher/dialog/LauncherFrame.java#L127

**Comment by Penagwin** [comment]
Unless they are on windows we can't tell, so we either need to make the "Java 32bit on a 64 bit System" variable. Then however, it will never show on non windows computers. 

We may as well nag them to either check themselves, or upgrade right? If modpacks won't run with 32bit either way...

Question: Add this as an option to warn in the modpack itself? As well as the status url?

**Comment by Slind14** [comment]
@Penagwin please take a close look at the source code and the stackoverflow link I pasted. This one is really only needed on windows as windows does lie when the general one is used.

**Comment by Penagwin** [comment]
@Slind14 Yea, but newer modpacks like alice need 64 bit, or they simply will not run. So only warning the user if they have a 64bit system with 32 bit java doesn't cover those with just  32 bit systems.

**Comment by Slind14** [comment]
I have no idea on what you want, all the things I could think of are possible.

**Pull request closed without merging**
