### PR TITLE
Fix for issue 235

### PR DESCRIPTION
**Pull request by mindw0rm**
This is a fix for https://github.com/SKCraft/Launcher/issues/235
- read new version_manifest.json and take URL for VersionManifest from there
- handle format changes in the version manifests after 1.12.2
- bugfix in VersionManifest: if libraries is a LinkedHashSet, some data got lost
  during parsing - some libraries were missing completely, others lost their natives
  which is also the reason why the native lwjgl libraries were missing

### CODE REVIEW

**Comment by mindw0rm** [comment]
I tested this with 1.12.2, 1.13.2 and 1.14.

**Comment by SDUBZ** [comment]
@mindw0rm was this built with gradle 5.0 because i tested your changes myself and got "FAILURE: Build failed with an exception.
14:14:36.653 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:14:36.653 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:14:36.653 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':launcher:compileJava'.
14:14:36.653 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Compilation failed; see the compiler error output for details."

**Comment by mindw0rm** [comment]
I'm afraid the fix is not yet complete - after looking a bit into the fabric issue (#300) [hint: the fabric installer misses the required install_profile.json], I noticed that [the way the PackageBuilder changes the command line arguments](https://github.com/SKCraft/Launcher/blob/master/launcher-builder/src/main/java/com/skcraft/launcher/builder/PackageBuilder.java#L160) is not compatible with the version manifests of 1.13+ - since the string `minecraftArguments` is null/does not exist any more and instead, an array property `arguments` is used. 

Imho the proper way to solve this is to add `addVersionIndependentMinecraftArgument` (or `addVersionIndependentMinecraftArguments`) to VersionManifest and use that in the PackageBuilder.

**Comment by mindw0rm** [comment]
It's even worse: the format of install_profile.json in Forge 1.13 is *completely* different from that of 1.12.2 :(

**Comment by spannerman79** [comment]
> It's even worse: the format of install_profile.json in Forge 1.13 is _completely_ different from that of 1.12.2 :(

It will be safe to assume to skip forge for 1.13. Rift stepped up when the forge dev team took too long.  Now its fabric for 1.14.

**Comment by mindw0rm** [comment]
Rift doesn't have an install_profile.json either. There is a profile.json, but that one has yet another format. 

So Rift also won't work without changes to the PackageBuilder.

**Comment by spannerman79** [comment]
An update:
https://github.com/FabricMC/fabric-meta#v2

```
loader should depend on intermediary
all intermediary is is a "mappings/mappings.tiny" file dropped on the classpath
as long as it is there, it will work, any order
```

**Comment by SDUBZ** [comment]
is this tiny mapping located in the github or do i have to compile my own tiny mappings?

**Comment by SDUBZ** [comment]
@sk89q what was spanner talking about the class path? not really versed in code

**Comment by sk89q** [comment]
@SDUBZ classpath is just a list of places Java has been told to look for additional Java code when something requests it

i.e. game uses a game engine called Blocks. Well, Blocks has to be on classpath for the game to be able to make use of Blocks

but this looks like a complicated issue

**Comment by mptorz** [comment]
@mindw0rm I tested with 1.12.2 and forge. No success. Still getting 
```
To report this error, please provide:

java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:165)
	at com.skcraft.launcher.update.Updater.call(Updater.java:92)
	at com.skcraft.launcher.update.Updater.call(Updater.java:35)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Irgendwer01** [comment]
@mindworm is this PR still active?

**Comment by Irgendwer01** [comment]
@mindw0rm is this PR still active

**Comment by spannerman79** [comment]
Learn how PR's work @Irgendwer01  https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by mindw0rm** [comment]
I haven't tested it with newer versions, and it's known that it's insufficient for modpacks, but I see no reason to withdraw it. 
Dunno how up-to-date it is, since I haven't found time to do anything since more than a year ...

**Comment by hedgehog1029** [comment]
Superseded by the changes in master; thanks anyway!

**Pull request closed without merging**
