### PR TITLE
Updated To Gradle 2.8

### PR DESCRIPTION
**Pull request by jtrent238**

### CODE REVIEW

**Comment by Leeo97one** [comment]
Wow, very useful... I think sk89q has enough skill for update that without a pull request.

**Comment by jmarler** [comment]
+1 this update. This has been sitting around a while. It would be nice to see it merged.

**Comment by wizjany** [comment]
all jokes aside, randomly changing gradle versions has the potential to make builds nonfunctional with some projects due to feature incompatibilities with some plugins or configurations. there's no reason to fix something that isnt broken, as they say.

that said, there's also no reason to bump 5 month old issues just to make pointless remarks

**Comment by jmarler** [comment]
If there are issues upgrading Gradle, this would be a great place to mention them so that we can work through them. It appeared to me from the initial comment that this would be updated without the pull request. Considering the fact that it is now five months later, and that has not happened, I wanted to indicate that I would also appreciate an update. There is no need to be hostile.

**Comment by wizjany** [comment]
There is no reason to upgrade. That's it. No one has presented outstanding evidence that an upgrade is necessary. You said it would be nice to see it merged, but for no reason whatsoever. The commit message even has a typo in it.

Also, I never said there are issues, I said there can potentially be issues, so it's unwise to change versions "just because" someone wants to commit something to the project. As mentioned 5 months ago,_ if SK sees the need_, he's more than capable of doing it on his own.

**Comment by jmarler** [comment]
If there is no reason to upgrade, and you don't like the typo, then reject the request and be done with this. There is no reason to be so hostile. If you want to continue to receive assistance from the community of users who use your projects, I would suggest you tone down the condescension. If you do not want assistance from the community, then close the project, and we will not trouble you ever again with our pointless requests or remarks.

**Comment by wizjany** [comment]
I'm not even affiliated with this project (note the distinct lack of the [badge](http://i.imgur.com/YbX2p4M.png) next to my name) or I would have closed it ages ago. Perhaps you should tone down the assumptions and just take my opinions for what they are - my opinions.

You could also stop strawmanning and actually answer the point of my argument - what value does merging this PR actually give the project?

**Comment by jmarler** [comment]
Does it matter? We can all view the changelog for Gradle and see the benefits of moving to a new release, but if you are not affiliated with this project, then you are simply trolling. Collecting any amount of information to support this request will change nothing as you have no control. If you want to know what is compelling about moving to a newer release of Gradle, then I suggest you go read the changelogs. Change is not always about fixing something that is broken, often times it is about improvement, even simple incremental improvements like moving to a newer release of a critical toolset that brings better performance and compatibility with newer java releases for example.

**Comment by wizjany** [comment]
[X] Still strawmanning
[ ] Actually pointing out benefits of a newer (actually old by now) gradle release

**Pull request closed without merging**
