### PR TITLE
Replace widowHeight with windowHeight.

### PR DESCRIPTION
**Pull request by miiichael**
Hi, this is my first PR; I hope I'm doing it right. It's just a spelling correction.

### CODE REVIEW

**Comment by wizjany** [comment]
Note that changing this will break existing configs that already have it set via the ```widowHeight``` key. It's not a huge deal but it means anyone with an existing launcher who upgrades will have to resize their window again.

**Comment by DarkGuardsman** [comment]
could add a small piece of code to automatically port the values in the config

**Comment by wizjany** [comment]
possible yes. but imo it isn't necessarily worth adding or even changing in the first place.

**Comment by DarkGuardsman** [comment]
True, just offering a suggestion while I read through the src code. I still recommend adding the code in case you need to update the configs for other reasons. As the base code for this would be reusable for any config editing.

**Comment by hedgehog1029** [comment]
I think this should be fixed but given that this PR is old and currently conflicts I might just fix it myself. Leaving open in the meantime.

**Comment by hedgehog1029** [comment]
Fixed in 27da4e8e4c7275601a440e6933ce4dfb6c14f9c0

**Pull request closed without merging**
