### PR TITLE
Create HELP!

### PR DESCRIPTION
**Pull request by TnTexplode**
Please read, SKCraft

### CODE REVIEW

**Comment by TnTexplode** [comment]
Email: trthalacker@outlook.com

**Comment by spannerman79** [comment]
PR's are not for creating issues or for requesting help.

Read https://guides.github.com/

**Comment by jtrent238** [comment]
you need to run `build.bat` and go to `launcher-fancy/build/libs/`

**Comment by TnTexplode** [comment]
Well, i do that and Gradle fails

**Comment by jtrent238** [comment]
can i have gradle log?

**Comment by TnTexplode** [comment]
How?

**Comment by sk89q** [comment]
Make a ticket under Issues at least.

**Pull request closed without merging**
