### PR TITLE
Linux XDG folder support

### PR DESCRIPTION
**Pull request by cking**

### CODE REVIEW

**Comment by hedgehog1029** [comment]
While you're free to apply this to your own launcher fork, I can't apply this upstream because it breaks existing launcher installations on Linux.

The [Rust bootstrapper](https://github.com/SKCraft/rusty-bootstrapper/) has better per-platform data directories, but it isn't quite ready yet. Unfortunately I've been blocked for a long time by Mac support; I need a mac dev to help me add progress bar support to native-dialog-rs.

**Comment by cking** [comment]
Would it work, if I add a fallback to use the original logic if the XDG part isnt specified? Meaning, it wouldn't break old launchers? :)

**Comment by hedgehog1029** [comment]
Yeah it would have to check for the old data directory before trying to use the new one.

I would like to finish the rust bootstrapper as well - it's moved back up my todo list somewhat.

**Comment by cking** [comment]
alright, i will rework that part.

**Comment by cking** [comment]
done :)

**Comment by hedgehog1029** [comment]
@sk89q depends how much Rust you know!

I chatted with a friend who has some Rust on Mac knowledge and they gave me a couple pointers, so when I have a bit more time on my hands I'll get back to it...

**Pull request merged**
