### PR TITLE
Browser with html5/css/js support

### PR DESCRIPTION
**Pull request by AndreyMrovol**

### CODE REVIEW

**Comment by spannerman79** [comment]
Have you compiled and tested against JDK8 @AndreyMrovol ?

**Comment by AndreyMrovol** [comment]
jdk version: jdk1.8.0_211

```
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :

*******************************************
 You are building SKCraft Launcher!


 Output files will be in [subproject]/build/libs
*******************************************


> Task :launcher:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6

> Task :launcher-builder:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6

> Task :creator-tools:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :launcher-bootstrap:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6

> Task :launcher-fancy:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 41s
24 actionable tasks: 24 executed
Press any key to continue . . .
```

**Comment by AndreyMrovol** [comment]
jdk 8u211

```
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :

*******************************************
 You are building SKCraft Launcher!


 Output files will be in [subproject]/build/libs
*******************************************


> Task :launcher:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6

> Task :launcher-builder:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6

> Task :creator-tools:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :launcher-bootstrap:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6

> Task :launcher-fancy:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 41s
24 actionable tasks: 24 executed
Press any key to continue . . .
```

**Comment by AndreyMrovol** [comment]
> Have you compiled and tested against JDK8 @AndreyMrovol ?

@spannerman79

**Comment by lucas19961** [comment]
Works very well

**Comment by KarmaConfigs** [comment]
There was an error java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at com.skcraft.launcher.DefaultLauncherSupplier.get(DefaultLauncherSupplier.java:24)
	at com.skcraft.launcher.DefaultLauncherSupplier.get(DefaultLauncherSupplier.java:14)
	at com.skcraft.launcher.Launcher.showLauncherWindow(Launcher.java:377)
	at com.skcraft.launcher.Launcher$3.run(Launcher.java:428)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 more

Please, help

**Comment by oxodao** [comment]
> 
> 
> There was an error
> 
> `java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel at com.skcraft.launcher.DefaultLauncherSupplier.get(DefaultLauncherSupplier.java:24) at com.skcraft.launcher.DefaultLauncherSupplier.get(DefaultLauncherSupplier.java:14) at com.skcraft.launcher.Launcher.showLauncherWindow(Launcher.java:377) at com.skcraft.launcher.Launcher$3.run(Launcher.java:428) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) at java.base/java.security.AccessController.doPrivileged(AccessController.java:389) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 17 more`
> 
> Please, help

You don't have JavaFX. If you are on linux there is a package for that

**Comment by jkroepke** [comment]
JavaFX is gone in newer java versions?

**Comment by KarmaConfigs** [comment]
> JavaFX is gone in newer java versions?

Yes, I guess you have to download it manually or import into the project, I don't remember the way you have to do in newer java versions, but it's a problem

**Comment by jkroepke** [comment]
What about https://github.com/chromiumembedded/java-cef ?

Instead a JavaFX browser which is not maintained anymore a state of the art browser which understand latest web features?

**Comment by hedgehog1029** [comment]
I would be against using a CEF browser. JavaFX is still supported, it's just not bundled with the JRE past java 10.

Personally I think that this is out-of-scope for the base launcher, but you are obviously free to include it in your local copy.
I see little reason to support running Javascript in the launcher webview, it's just meant to provide a space for a basic newsfeed.

**Pull request closed without merging**
